language: rust
rust:
    - stable
    - beta
    - nightly
sudo: false
dist: trusty
os: linux
cache:
    directories:
        - $HOME/.cargo
        - target
env:
    global:
        - secure: "cuxSfNDV/1p9qIXMbj02KfI+n6EdWV3DOsR9hx8qJDySVlFznH9Hg//fmvqfsqrG+FKSLMUx+ki34wAk0/9/1//SCSg24uSCMd6Qw+jRz/+PY1EKYhVKe7lvhdRyYNHLK7F3sFt/9+zuZIkNg446ATIdKCn4Te6g+m5XJOB5qJy1qGCCcrQzyTADqOut2E+0rzW6mf6XCzpekEYq1/w2EyfArG5cQDCQUCH9Ugdw6rYZV7nWpyySRCYPupjs2tmxEbAUb9hQfZXNh4FBdg6A5ybK41W/gJOXe1+C9XzKEFdWoWRbl5LSYZ2AtMf21w2u8vUZ7fRtKtBiJghHHF+j6hsUDMKMueSpjnnRhsN17lPo/UHucTz15F3iV6CN1ietfWTdhbBbvzlZT4TkxqWHqtnrKVx090+fnY4kX3lmO4+Qb8/+JwCuvxQgluBbj4ZTrrWqwlJrqP/0Bo0bmuwp8mwOr6Z//ysjqAwvRQA1/e7KSTAr3nC3z0tGisXAqZbTsHnY/XLiN2EaZhMKdgQ211xwsVHjAfbuvVv/ciUEXTsAUFtYy6+sLP6SO3KBlygJTkq80TaQfro5Lb8BqjLI6PH4lpDLXXtXhvwMAMqnGLA8DTmL0CWnIlyr0WxH3yJJ5D0sgMdh0ze9alRnAjo+eTJFtj4gJPMQhsyuC999xm0="
        - secure: "FcsYL3ETIDEOX41etvJfhkSOKHTNbh7iEtr3SvCIFcAvzPISV7NjUptdmcNvbB7RxnZMunjnAac+Aan9imFsxZn8VrVAQ0I3TxBXmT0gUSs5F1b6L8Ca1F/yTb5BwGKBEX6ZfOW0ww1/EBAoO0lVq/CWBRJTytycJR/Znyax583FRZA50sEKK3Kdxc2HTvAG2ok3o+c7owfMSEvDV/lTEjPdKKe4uu2mk8H4Dhc8fwrqf+i53Q9PFl2LXM2fwSsbzqTSy75YKjEB+0SfFOwHn8o9vRoCvj3emgTsImnls/PG+j6LivhosNy9ZOUnY9jWDR+GpbQhO2ry9D/SkyHQ10DbcIBbIFxPzfthNyX4RgKwplrtetAq35cg9euXzDG5+KU2oAdpRhS57eYwNqV+OSeD3TzoO76shCOJEmxjef/C4mynzaZ5QnPbOE51E3+52J/R8Eacz1XzgxvF2X5qeq+IMoiXLBWFB6OjOaieaMIk9NFX3BA6s8KaGYi9C0e2UeYcAPiGbppOmEKwBcIRNWWYwObxnFI6GcPRaMV/8fJN6UEsmXGVhNZgs+b2mv8p4LuUbOFzqVuMeBK9PjT5qih5BerRwNzj6D2UiJA2rD+vB6SQ0DM893wyzJO9A1Ns4Okx3mDfZJ4P7AfSTAyvfYHptSXDca6ZVDIGnCxRxcw="
    matrix:
        - CARGO_FEATURES=
        - CARGO_FEATURES=smallvec
before_script:
    - curl -L https://github.com/arcnmx/ci/archive/master.tar.gz | tar -xzC $HOME && . $HOME/ci-master/src

script:
    - cargo build
    - cargo test
    - cargo test --release

deploy:
    provider: script
    script: "true"
    on:
        tags: true
        all_branches: true
        condition: "$TRAVIS_RUST_VERSION = stable && -z $CARGO_FEATURES"

before_deploy:
    - cargo doc
    - cargo package

after_deploy:
    - cargo pages-publish
    - cargo publish
